//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwsTools {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ToolkitSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ToolkitSettings defaultInstance = ((ToolkitSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ToolkitSettings())));
        
        public static ToolkitSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZonomiApiKey {
            get {
                return ((string)(this["ZonomiApiKey"]));
            }
            set {
                this["ZonomiApiKey"] = value;
            }
        }
    }
}
